baseURL = "/"
languageCode = "en-us"
title = "Electronic Lab Notebook"
theme = "temple"
# If not set, it will not appear. Otherwise it will show below your footer links
copyright = "(c) 2018 -- All rights reserved."
googleAnalytics = ""
disqusShortname = "Research Notebook"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
# enable emoji use, i.e. :smile:
enableEmoji = true
#pagination = 10

[params]
  subtitle = "Elise Gould's Electronic Research Notebook"
  description = "A website built through Hugo and blogdown, used as an Electronic Lab Notebook (ELN)."
  
  # Enables syntax highlighting
  highlight = true 
  
  # Supports highlighting for languages not included in the original pack
  # See https://highlightjs.org/download/ for original pack
  # For reference to all languages, see:
  # https://github.com/isagalaev/highlight.js/tree/master/src/languages
  hjslangs = ["go", "vim", "shell", "bash", "markdown", "r", "python"]
  ## NOTE: 
  ## have made edits to Lab_notebook/themes/temple/layouts/partials/css/custom.css
  ## which allow changing the highlighting theme by editing Lab_notebook/themes/temple/layouts/partials/header.html

  # Enables the topmenu, which pulls from categories
  topmenu = "categories"
  
  #MathJaxCDN = "//cdn.bootcss.com"
  #MathJaxVersion = "2.7.1"

[params.logo]
  url = "notebook.png" 
  width = 50
  height = 50
  alt = "Logo"

# Builds a list page for each category given
[taxonomies]
  tag = "tags"
  category = "categories"

[author]
  name = "Elise Gould"
  github = "egouldo"
  email = "elise.gould@unimelb.edu.au"
  twitter = "EliseGould"
