---
title: "research_proposal"
author: "Elise Gould"
date: "19/12/2017"
output: html_document
bibliography: ../../static/files/citations/posts_read.bib
---

Max 5 pages, 3000 - 4000 words.
Send to committee and cc'd to rhd-biosciences@unimelb.edu.au

- are topic and aims well defined and achievable
- are the appropriate methods established or will they need to be developed
- does the student understand the relevant literature
- are there any intellectual property issues
- current / potential EHS issues?

# Introduction

- well-referenced intro that explains scientific context of project (1 - 3 pages)

# Project Aims and Outline

- an outline of the major aims of the project and the approaches that will be taken (1 - 2 pages)


target audience:

scope: Am i examining just models... or am I looking at the entire decision-making process... from specification of objectives, for example.. My feeling is that there are a lot of papers focusing on good / robust modelling practices within ecology / conservation in general, as well as articulating why models are necessary in decision-making. I think it could be useful to consider the entire process to developing the decision tool as a whole because aspects of the whole process may influence the final decision.. For example, Law et al.  [-@Law:2017ia] argue that decisions are sensitive to the scenarios selected during scenario analysis.

## Paper 1

## Paper 2

## Paper 3

# Timeline of activities and goals

- timeline of activities and goals for first 12 months of candidature (GANTT chart),
including preparation of the confirmation report and holding the confirmation meeting (9 - 10 months)

# References
