---
title: first post
author: Elise Gould
date: '2017-12-12'
slug: first-post
categories:
  - reading
  - planning
  - todo
tags: []
---

Readings: Reproducibility – how to define for this context. Ecology / decision support tools.

Reproducibility of ecological models used for decision support tools. 

Interested in the sorts of decisions that we make as modellers… e.g. what performance measures do we use, there are so many different ways of valuing the objectives. And depending on which measure you use, you might judge the outcomes of each of the different strategies under consideration differently…. Resulting in a different decision.

Solutions focused, rather than focusing on identifying problems around reproducibility. Want to be instead using outputs where other people have identified those issues (e.g. Ash and Hannah’s surveys). 

One question is going to be, what is the cost of those solutions… model-building is already so labour-intensive. And what is the relative benefit of those solutions? Does it change the decision?
