---
title: meeting april 12 2018
author: ''
date: '2018-04-12'
slug: meeting-april-12-2018
categories:
  - meeting
  - planning
tags:
  - systematic review
bibliography: ../../static/files/citations/posts_read.bib
---

Planning the projects and the scope of the Phd (and the format for the thesis):

- Perfectly acceptable to have disparate projects / papers comprising the thesis, and bound together with a good introduction and conclusion.
- Don't have to choose between different projects.

Good to try and sit with that tension, and not having to resolve it by having a neat / tightly fitting narrative thesis.

Hannah: working on structured decision making tool with Libby. Would appreciate having guidance on how to avoid reproducibility issues / QRPs during the process.

Thursdays sit in with Fiona and Hannah.
 
Where to start to begin picking up momentum again: 
- just start at the easiest point.... Have done a lot of work on the systematic review plan, let's start there.

Time for advisory committee meeting:
- send email off.... week of the 28th of May.
