---
title: Madin (2007) Advancing ecological research with ontologies
author: ''
date: '2018-02-24'
slug: madin-2007-advancing-ecological-research-with-ontologies
categories:
  - reading
tags:
  - ecology
  - research practice
  - ontology
  - informatics
  - open data
header:
  caption: ''
  image: ''
bibliography: ../../static/files/citations/posts_read.bib
---

[@Madin:2008jv]

# Why are ontologies relevant to ecology?

Issue of effectively locating scientific data is hampered because our current approaches for describing it rely on the "ad hoc use of user-supplied keywords, and do not ensure that such terms are defined and used consistently."
The same is true when searching for relevant data, "users supply their own search terms, which are then matched against keywords assigned to datasets". Ecology is particularly prone to this problem, and many terms often have multiple and variable meanings in different contexts. Ontologies can overcome this problem because they "provide a formal representation of the terminology and concepts in a scientific domain, which can be used to clarify the relationships among those terms and concepts".

Ontologies are proliferating in molecular biology, and biomedical communities. Broader benefits include: closer collaboration, better synthetic analyses, and greater data-sharing capabilities. An example of a successful ontology, is the gene ontology consortium, whereby they unified the terminologies from different model-organism domains (fruit fly, mouse and yeast) to improve querying across their major database efforts. 

## What can we do with ontologies in ecology

Not an esoteric point!

What properties of ontologies facilitate data-sharing promise of ontologies in ecology? They hold promise as a "unifying mechanism for representing knowledge because they are interpretable by both humans and computer applications, and subsequently facilitate the use of automated reasoning for helping with arduous data management tasks that scientists deal with on a daily basis".

Advanced information discovery in the context of ecological data landscape: Large amounts of ecological data are increasingly available for research, but finding data relevant to a given study is still difficult. 

By mapping data points onto datasets "semantic annotation" advanced information discovery is possible. Can even have multiple annotations.. perhaps by different scientists. That way it's simultaneously useful for separate lines of inquiry, or to capture differences of opinion about what the data represent.

# State of ontology research in ecology

Very, very slow uptake. The authors state that this is because ontology and its requisite supporting application development are both widespread and well funded activities. They also argue that there is limited success because (comparatively) ecological research spans broad and interelated topics, and data are often collected for a targeted purpose. Without considering how they might be reused for broader projects and analyses.

## Ontology development in ecology

The authors categorise three types of ontologies th8are are important in ecology, and give some selected examples:

1. Domain-specific ontologies: "focus on capturing terminology used in specialized scientific disciplines or communities"
2. Framework ontologies: "define general concepts and relationships that others can extend when building domain ontologies"... "They are designed to interconect existing domain-specific ontologies while providing a consistent foundation for future ontology-building efforts." There are a number of ontologies in development that aim to describe ecological and environmental data, especially because observations and measurements are the primary information expressed within most scientific data. Framework ontologies can support "generic and flexible data management systems for diverse and non-standardized ecological and environmental datasets"
3. Other approaches (i.e. non-ontological): Less-formal approaches, such as controlled-vocabulary, provides a set of selected terms or keywords that denote a distinct concept. A glossary is an extension of a controlled-vocabulary. They can elimiante problems with term ambiguity, and other natural language complications. However, their informal nature limites their ability to support data searching and integration tasks that rely on automated reasoning.

## Incorporating ontologies in ecological information management

Ontologies can aid in scientists utilising and publishing ecological and environmental data. See Figure Below:



# Relevance to my research

# References
