---
title: "PhD Research Proposal: Reproducibility and Transparency of Decisions in Ecology and Conservation"
author: "Elise Gould"
date: '2018-05-23'
output:
  word_document: default
  pdf_document: default
  html_document:
    keep_md: yes
number_sections: yes
categories: ["planning"]
slug: research_proposal
tags: ["project"]
bibliography: ../../static/files/citations/research_proposal.bib
---

*Keywords:*

- conservation
- decision-making
- ecology
- reproducibility
- structured decision-making

# Introduction

Successful biodiversity conservation and management is underpinned by effective and robust decision-making [@Mukherjee:2018cb]. Decision-makers are tasked with allocating limited resources in the face of uncertainty about the effectiveness of alternative management interventions, and incomplete or inadequate scientific information. Moreover, environmental decisions often must be made in complex socio-economic and political contexts, with multiple stakeholders and multiple and/or competing objectives. Formal, structured approaches to decision-making under uncertainty, such as Structured Decision Making, are both implicitly and explicitly espoused as a pathway to more robust and reproducible conservation decisions [e.g. @Moore:2012ii; @Converse:2013wp; @Schreiber:2004to]. However, this claim to reproducibility remains untested, and a more nuanced consideration of what exactly reproducibility means in this application is lacking. Given that science is said to be in the grips of a “reproducibility crisis”, and that biased and unfair scrutiny in the broader socio-political climate of “alternative facts” threatens credibility of scientific knowledge [@Baillieul:2018jd], it is both essential and timely that the reproducibility of decision-support in ecology and conservation is given rigorous research attention. 

Failure to reproduce a large proportion of published studies in the fields of psychology and medicine has received considerable attention and provoked heated discussion among researchers in the broader scientific community.  Scientific credibility is underpinned by the assumption that findings are both real and replicable [@Nakagawa:2015bn]. As the recent “reproducibility crisis” debate illustrates, this assumption is often incorrect [@Nature:un].  For example, the Open Science Collaboration’s Psychology Reproducibility Project reported that less than half of published results could be reproduced [@OpenScienceCollaboration:2015cn]. Although large-scale direct replications are largely absent in ecology [@Nakagawa:2015bn], an initial assessment of the conditions found to foster reproducibility problems provide evidence that ecology as a discipline is at risk of a “reproducibility crisis” [@Fidler:2017he]. 

## Research scope: reproducibility *of* decisions versus reproducibility *for* decision decisions

Reproducibility research in ecology has largely focused on the primary evidence-base. I draw on the conservation decision-making (CDM) literature to distinguish between knowledge generated at the level of the individual study level (“primary evidence base”), and the translation of that information into a decision [@Dicks:2014gf], whereby evidence is collated, synthesised, and transformed into decisions, ideally using some formal decision support system [@Gardner:2018dm]. Most decision support systems developed using a structured framework utilise one or more “decision tools” at various steps in the decision-making process, comprising conceptual or mechanistic models, representing all or part of the system in question [@Dicks:2014gf, see discussion point in Chapter 3 for a definition of the distinction between tools and systems].

One exception to the focus on the primary evidence base, is Morrison et al.’s [-@Morrison:2016cd]replication study of the Population Viability Analysis literature. They discuss the potential implications of the non-reproducibility of studies and models on the decision-making process. Firstly, non-reproducible predictions undermine the credibility of the original model, and therefore any decisions informed by that evidence. Any predictions are therefore unreliable, and may result in finite resources being directed inefficiently, and in opportunity costs. Thirdly, the effectiveness of an intervention may not be able to be evaluated against the predictions of the model if they are not reproducible. The ability to compare the outcome of an intervention against model predictions, and hence to measure progress towards the conservation objectives, is especially important in ecology and conservation: true randomized experimental design is often infeasible, such that the performance of a conservation action is measured against the counter-factual, which is often estimated using predictive models [@Law:2017ia]. Finally, if the original model predictions cannot be reproduced, the decision-maker is prevented from comparing and evaluating revised models with updated parameters against previous models. This is relevant for contexts where decision-making is informed by ongoing monitoring programmes, such as in adaptive management-based conservation. 

This work is a good initial consideration of how reproducibility issues might impact decisions, and it echoes work in the conservation decision-making (CDM) literature underscoring the importance of a ‘robust’ evidence-base for informing management [@Dicks:2014gf; @Law:2017ia; @Sutherland:2017hc; @Gardner:2018dm]. While reproducibility for decisions – or the reproducibility of either raw evidence and/or decision-tools generating information informing decisions – is important, it fails to consider the broader decision process in which conservation decisions are made, and explicitly assumes that if the evidence-base is reproducible, then this should translate to reproducible decisions. Yet, decision-making is a “human enterprise” shaped by values and expectations [@Mukherjee:2018cb] and failing to integrate the human elements of decision-making in conservation may lead to sub-optimal outcomes [@Bennett:2017jh].  For this reason, I argue that reproducibility research in ecology and conservation should certainly continue advancing for the primary evidence-base, however, the scope of research should extend beyond evidence-generation, to examine the systematic use and synthesis of that evidence to inform decision-making. The focus of my PhD will therefore be on the reproducibility of decisions: or whether the entire decision-process can be repeated to reproduce the same decision.

Below I propose some examples of ‘decision-points’ within the broader decision process that may impede the reproducibility of a decision. These are points of departure or variation occurring within the development of a DSS that may result in a different decision-outcome, should the process be repeated – either by the same analyst in the future, or by another independent analyst.

1. Problem formulation is a critical phase of the decision process but is often neglected or at least poorly documented when it comes to published applications of decision support systems in ecology and conservation. Human values shape preferences about the acceptability of decision outcomes in terms of fulfilling conservation objectives and should therefore be properly captured in objectives and performance measures [@Conroy:2013tc]. Decision modelling outputs may be sensitive to the specification of the performance measure [-@Giljohann:2014tv]. Failing to properly incorporate decision-maker and stakeholder values may therefore influence the reproducibility of a decision, resulting in sub-optimal decisions that do not adequately meet the true objectives.
2. Scenario analyses are often used to make a case for implementing one management strategy over others. However, Law et al. [-@Law:2017ia] emphasise that the selection of scenarios may influence inferences about the appropriate course of action – choosing scenarios that are impossible or highly improbable may yield the impression that a particularly positive or negative outcome is likely. Thus, it is not only the modelling inputs into decisions that should be scrutinised in terms of reproducibility, but also the choice scenarios we wish to run through them. 

## Research aims and objectives

This major goal of this PhD is to investigate the transparency and reproducibility of decisions generated from structured approaches to conservation decision-making (such as Structured Decision Making, SDM). The first aim of this research is to expand and develop a conceptual understanding of “reproducibility” that is fit for application in conservation decision-making. Existing approaches to reproducibility almost exclusively focus on hypothesis-testing based research, however in applied ecology and conservation technical approaches draw primarily on decision-analytic tools and methods for decision-making. This typology of reproducibility will be sensitive to the particularities of the data, methods and questions commonly encountered within this context. By taking decision-support systems (DSS’s) as its unit of interest, this research aims to identify critical points in the decision process that threaten the reproducibility of ecological decisions and undermine conservation success. Secondly, I aim to systematically review the published literature on decision support systems to evaluate the magnitude and extent of the “reproducibility crisis” in translational research of ecology and conservation. This review will allow the development of a set of guidelines or a check list for improving the transparency and reproducibility of decision support systems in ecology and conservation. Finally, I aim to use real-world decision problem case studies to investigate the replication of decision support systems.


# Reproducibility for decision support in ecology and conservation: towards a formal typology 

## Surveying the reproducibility literature in ecology and conservation

There appear to be two strands of reproducibility research in ecology. The first, termed “reproducible research” by some [@Peng:2009vn; @Gandrud:2016ux], targets the research practices of individuals, and considers reproducibility to be largely computational in nature. It draws on the computational biology and scientific computing literature to proffer technological solutions with an emphasis on software and data management practices. It is closely linked to work within the open data movement in ecology. The second and more recently emerging major strand of reproducibility research draws on meta-research approaches within psychology, medicine, and science more broadly. 

“Reproducible research” focuses on the data analysis pipeline for a single analysis or study, taking the starting point for reproducibility to be where analysis is ready to begin (data is on hand and probably digitised). These approaches seem to resonate among ecologists, with much reflection and discussion in the grey literature, particularly in blog and twitter format. Practices for improving computational reproducibility have included version control with incremental changes, functional programming and unit-testing Wilson et al. [-@Wilson:2014ck]. Others have emphasised the use of literature programming techniques and containerised analyses that link code to their inferences in a single document [@Baumer:2015hc; @Gandrud:2016ux]. Noble et al. [-@Noble:2009da] describe how to organise computational biology projects while the British Ecological Society have published complete guides to reproducible code and data management [British Ecological Society 2014; @BES:tGdddZne].

The “open data” movement within ecology, and science more broadly, assumes more of a systems-level view of reproducibility: situating the reproducibility of individual studies within the broader life-cycle of scientific research. Some computational ecology research in this context is still targeted at improving the research practices of individuals, however, the overarching aim is to improve the computational reproducibility or research in order to facilitate large-scale meta-analyses [@Merali:2010tw], longitudinal studies and data synthesis [@White:2013ea]. Solutions arising from the open data movement are a mixture of technological and policy-based. For instance, White et al. [-@White:2013ea] discuss the particularities of ecological data and describe methods for ensuring data is re-usable to others; while Ram [-@Anonymous:a1kBf1q9] illustrates how git and GitHub can facilitate greater reproducibility and increased transparency. Similarly, Whitlock [-@Whitlock:cl] describes the technical and cultural issues that must be addressed to increase data-archiving practices in ecology and evolution, including journal policy. For most in the open data movement, the responsibility for reproducibility is shared among individual researchers, journal editors and reviewers for improving reproducibility via openness practices and policy [@MoruetaHolme:2018bi]. 

Meta-research approaches include the identification of the types of, and evaluation of the extent of questionable research practices (QRPs) across whole disciplines  [e.g. -@Fraser:2018cl], as well as understanding the broader set of conditions fostering their occurrence and prevalence, such as a lack of transparency and publication bias in a publish-or-perish environment [@Parker:2016hc]. Large-scale meta-analyses are a new and emerging technique for evaluating whole fields for reproducibility, but have not been undertaken in ecology and evolution to date [@Fidler:2017he], even though traditional meta-analyses are not new [@Stewart:2010fh]. Conceptual understandings of reproducibility extend beyond computational reproducibility, with numerous ‘typologies’ of reproducibility being suggested. Within such typologies, each type of reproducibility is understood as performing its own epistemic function. Solutions to mitigating reproducibility issues tend to target a community of practice, or the incentive structure, rather than individuals. For example, pre-registration of study designs may protect against QRPs including ‘p-hacking’, selective reporting and cherry-picking or HARKing (hypothesizing after results are known) [@Parker:2016hc]. Tools for Transparency in Ecology and Evolution (https://osf.io/g65cb/) provide a checklist to authors, reviewers and journal editors for improving reporting transparency. There is increasing uptake of checklists, including *Nature Ecology and Evolution* [@Nature:2018ud] and new guidelines for statistical practice for *Conservation Letters* [@Fidler:2018ho].

## Unpacking "reproducibility *of* decisions"

The term “reproducibility” broadly encompasses the ability to “replicate an experiment or study and/or its outcomes” [@Fidler:2017he]. In ecology and conservation decision-making, researchers the terms ‘repeatable’, ‘replicable’ and ‘reproducible’ are often used interchangeably and transparency is frequently touted as both a key-feature of environmental decision-support systems, and as central to delivering reproducible decisions [@Kim:2016gf]. However, the discussion of reproducibility in these contexts usually stops here, and there is no further discussion as to some definition of the term. McIntosh et al. [-@McIntosh:2011ew] elaborate further than most to explain the link between transparency and reproducibility in formal decision support for ecology:

> Transparent because rational explanations can be provided to support decisions, and because the user/stakeholder/citizen can reproduce the decision procedure, play with the weights, and perform sensitivity analysis to assess decision strength and robustness.

Examining this statement reveals that, at least for these authors, reproducibility is simply the repeatability of the decision procedure, or is reproducible ‘in-principle’. A study is replicable in principle if its methods, procedures and analysis are described transparently with sufficient detail to be repeated; whereas a study is replicable in practice if the original results can be reproduced exactly or with sufficient similarity (Fidler and Wilcox, 2018 in prep.). The repeatability of a decision procedure does not necessarily ensure that the resultant “decision” from the procedure can be reproduced; the above statement seems to imply that the transparency of structured approaches to decision making guarantees in-practice reproducibility, because it is reproducible in-principle. This assumption needs to be further investigated, especially given how commonly the inherent methodological transparency of SDM and other decision-analytic approaches is used as a justification for their use.

The above use of the term ‘robustness’ in the context of reproducibility of decisions also demands attention. Transparency and in-principle reproducibility of decisions generated from formal approaches to decision-making are commonly associated with delivering ‘robust’ decisions or management approaches [e.g. @Schreiber:2004to]. Few explicitly define what a ‘robust decision is’ – they are implicitly synonomous with ‘good’ or ‘accurate’, or else, are described as being ‘robust to uncertainty’ [@Moore:2012ii; @Converse:2013wp]. That is, robust management decisions are those that can tolerate some acceptable degree of uncertainty before the optimal decision changes [@Regan:2005wn]. 

Given the linguistic uncertainty around the properties of "reproducibility", "transparency " and "robustness " of decision support systems in ecology and conservation, a more thorough treatment should be given to defining the reproducibility of decisions. There are a number of existing typologies of reproducibility [e.g. @Nakagawa:2015bn; @Patil:2016tm; @gomez:2010rp] that may serve as the basis for formally defining a conceptual framework for the reproducibility of decisions. Each typology describes the different ways in which a replication study may differ from the original, with some being more finely specified than others. For example, Patil et al.’s [-@Patil:2016tm] typology is useful for highly computational analyses, outlining points of difference including the population, question, hypothesis, experimental design, experimenter, analysis plan, analyst, code, and estimate and claim. Gomez’ [-@gomez:2010rp] typology is less finely grained in terms of the classes of difference between a replicate and original; specifying site, experimenter, apparatus, operationalisations, and population properties. 

Gomez’ typology systematically considers how varying different subsets of those classes serves different epistemic functions, whereas Pattil et al. give minimal consideration of the epistemic functions of different types of reproducibility, distinguishing only between what they term “reproducible” and “replicable” studies ("reproducible": *Given a population, hypothesis, experimental design, experimenter, data, analysis plan, and code you get the same parameter estimates in a new analysis*, versus. "replicable": *Given a population, hypothesis, experimental design, and analysis plan you get consistent estimates when you recollect data and redo the analysis*). In contrast, both Gomez’ and Nakagawa and Parker’s typologies centre on the epistemic functions of generality and validity, which exist on a continuum. Nakagawa provide examples as to how these concepts might apply to ecological phenomena.

What Pattil et al. term ‘reproducible’, has been defined as “reproducible research”, or a set of minimum standards requiring that data and code is made available for others to verify results of the original study and for re-use of the data (Peng 2009). This type of “computational reproducibility” is advocated for as the minimum standard when there is a lack of time or resources for intensive replications [@Patil:2016tm; @Williams:2017bg]. As described earlier, “reproducible research" with an emphasis on computational reproducibility comprises the bulk of the reproducibility literature in ecology, perhaps because replications in ecology have typically been considered infeasible due to the inherent spatio-temporal variation in nature, or even unethical for work on threatened species (Nakagawa and Parker 2015). 

------

**Chapter One: Defining a typology of reproducibility for decision support systems in conservation and ecology**

A major aim of this PhD is to devise a typology of reproducibility that is applicable to decision support systems in ecology and conservation. A formal definition of the type, measure and purpose of reproducibility of decisions is necessary for evaluating the reproducibility of decision support systems. I aim to draw on work emerging within the second more recent strand of reproducibility research in ecology and conservation, advancing conceptual understandings beyond "computational reproducibility" and "reproducible research". I propose that the typology will synthesise some combination of existing typologies, such as the three described above. For example, Pattil et al.’s (2016) points of difference may prove useful for considering phases of the SDM process relying on complex mathematical models; while Gomez (2010) and Nakagawa and Parker (2015) may aid in understanding the epistemic functions of different types of reproducibility of decisions.

Most formal decision-support systems for ecology and conservation lie outside of the typical hypothetico-deductive model of science. Although the concept of reproducibility is not inherently specific to that model, the causes and solutions to the reproducibility crisis have focused exclusively on this mode. For instance, QRP’s including p hacking, cherry picking, and HARKing are specific to Null-hypothesis significance testing (NHST) (Fraser et al. 2018). Solutions to the reproducibility crisis, such as preregistration of analysis plans, are specifically targeted at addressing the cognitive biases that foster these QRPs, and so also adhere to this model of science. Measures of reproducibility, such as those employed by the COS reproducibility project have also focused on the hypothetico-deductive model of science, but not all.

The first step in building the typology is to define what constitutes a ‘successful’ replication of a decision support system. An obvious candidate is the final decision outcome, or the decision recommended at the end of the decision process. However, this will need careful consideration, depending on the type of replication being undertaken. For instance, suppose a ‘conceptual replication’ be undertaken to reproduce a decision support system for a particular decision-context. If the problem formulation phase is not constrained, it is possible that the set of potential decision alternatives might not even match those in the original study. This may occur because analysts vary in their ability to properly elicit the problem specification from decision-makers. The fundamental objective(s) might not be properly specified, or else the analyst might be be subject to ‘evidence complacency’ [see @Sutherland:2017hc] or be anchored by the alternatives proposed by the decision-maker, ignoring existing evidence and knowledge about the full range of potential decision alternatives for a given problem. The replicate and the original study would not be comparable in this situation, if the decision outcome is the measure of reproducibility.

Following that, key points of divergence in the decision process should be identified. I suspect these will map closely onto the different phases of the decision-framework being used. This is to facilitate the identification of different types of reproducibility, each serving different epistemic functions. For each type of reproducibility deemed relevant to conservation decision-making, the set of constraints and conditions constituting a successful replication must be carefully specified, in reference to its epistemic function. Some thought will also need to be given to how the epistemic functions are relevant to the context of conservation decision-making. For example, the importance of validity seems obvious – a replication supporting the validity of a decision recommended by the original DSS would also lend credibility to the decision process that led to that decision. However the relevance of generality to this context is not so obvious – does a conceptual replication that converges on the same decision as the original DSS give validity to the original decision, and / or does it tell us something about the applicability of the particular suite of tools built into the DSS for a given decision-context?

At present, the format this work will assume is unclear. It could be embedded in other chapters (Chapter 3; systematic review, or Chapters 4 and 5: the replication case study), or constitute a standalone chapter. 

------

# Identifying reproducibility issues for decision support in ecology and conservation: non-hypothesis testing based research

The reproducibility literature has focused exclusively on hypothesis-testing, whether that be Bayesian or frequentist. This also applies to initial research focusing on ecology and evolution. However, Fidler [-@Fidler:2016wv] correctly identifies that in applied ecological research, particularly in conservation science, non-hypothesis testing methods, such as decision-theory, cost-effectiveness analysis, optimization and other scientific computing methods are common. These approaches come with their own set of reproducibility issues. However, a full understanding of the types of reproducibility issues, as well as their impact on either the evidence-base, or the decisions informed by the evidence-base, is yet to emerge.

In what is likely the first reproducibility study in conservation, Morrison et al. [-@Morrison:2016cd] evaluate the Population Viability Analysis (PVA) literature by performing direct tests of repeatability and reproducibility: they found that poor model parameter reporting practices meant a large number could not even not even be reproduced in-principle, let alone in-practice. This work marks an important step towards identifying reproducibility issues relevant not only to PVA-based research, but also to CDM more broadly. Outside of ecology, where reproducibility research has received much more attention and focus, I could only identify a single paper that considered non-NHST based work in the reproducibility discussion. Crutzen and Peters [-@Crutzen:2017kn] suggest re-terming “power” and “underpowered” studies as being “undersamplesized”, in a move to embrace the disciplinary shift away from NHST towards inferences based on confidence intervals for effect size estimates. They exemplify such research as studies aiming to obtain accurate power estimates. Although their treatment of the issue is rather cursory, it is promising to see the scope of reproducibility research expanding to non-NHST approaches in broader science. However, it is pertinent that reproducibility research in ecology and CDM: we cannot evaluate the reproducibility of this body of work without first identifying relevant types of reproducibility issues.

------

**Chapter Two: QRPs for non-hypothesis testing research**

The first output for this research is to generate a “roadmap” of reproducibility issues, biases and questionable research practices (QRPs) that are encountered when developing Decision Support Systems in ecology and conservation. In this chapter I will attempt to identify where exactly in the DSS development process particular biases or ‘decision-points’ are likely to occur. This work should serve as a launching point for proposing standards and technical solutions targeted at individual (or teams of) researchers / analysts, with the broader objective of minimising the extent and magnitude of questionable research practices for DSS.

This chapter will constitute (from what I am aware of) the first attempt to investigate reproducibility issues for non-hypothesis testing based research. To this extent, the knowledge resulting from this chapter should also be applicable to other fields of science beyond ecology and conservation where translational research and non-hypothesis testing methods are prevalent. It will also build on the work of Fraser et al. [-@Fraser:2018cl] in advancing research on reproducibility and transparency in ecology.

*Methods for generating the roadmap*

1. Sketch out the SDM / DSS development process, but breakdown into modelling steps if necessary. As a starting point, I will take the Structured Decision Making process as the overarching framework for building a Decision Support System.
        a. Does this process differ for different tools / decision frameworks?
2. Identify sources of bias AND QRPs that others have identified in ecology and evolution, but also in other scientific disciplines and translational research fields
        a. at the individual DSS level
        b. at a higher level, e.g. in the evidence-base
        d. Are these biases / QRPs applicable to DSS's?
        e. are there other biases unique to DSS's that haven't been considered?
        f. Is their occurrence specific to the type of tool or application under consideration? i.e. are some tools more robust to biases / QRPs than others?
3. Map these biases / QRPs onto 1, where do they occur at the various decision-points?

I plan on utilising the outputs of the reproducibility discussion session planned for the Qaecera Retreat. The aim of the session is to initiate awareness and discussion among Qaecologists and Cebranalysts about reproducibility in our research practices, with the subsequent aim of equipping people with solutions to minimise or overcome these issues. The format for the session will involve structured / facilitated discussion in small break-out groups. Given the collaborative nature of this work, participants will be invited to co-author the paper after the retreat. This might also incentivise people to attend the session!

-------

# Evaluating the Transparency and likely reproducibility of decisions in ecology and conservation

Fidler et al. [-@Fidler:2017he]call for an assessment of the completeness and transparency of methodological and statistical reporting in journals for ecology. Such assessments should take the form of extensive journal surveys, with the aim of highlighting deficiencies in journal’s reporting policies. 

Why is it important: Incomplete reporting impedes direct replication, meta-analysis, and also direct re-analysis projects. From personal experience, I have reason to believe that incomplete reporting is rife in environmental decision support systems. In working with Bayesian Belief Networks for catchment management, it was impossible to re-build all but one system model from the published literature. At best, the causal structure of the model is reproducible, but only one published study I encountered contained sufficient information so as to reproduce its parameterisation. Importantly, there is also the issue of understanding modeller choices about how and why variables were parameterised. This information is rarely recorded, and often the source of empirical data used in parameterisation is not reported. The next chapter of my research will take up this call, where I will conduct a systematic review aiming to systematically evaluate the decision support literature in ecology and conservation for its transparency and likely reproducibility.

------

**Chapter Three: Systematic Review**

The roadmap of QRPs developed in Chapter Two will inform both the scoping and evaluation criteria for the systematic review. The results of the review will be used to generate a ‘reproducibility check-list’ or set of criteria for DSS in ecology and conservation. The check-list will be aimed at individual researchers, but with the hope of being adopted by relevant journals. The check-list will need to balance a sufficiently acceptable set of standards against resource constraints on individual researchers in order to prevent the check-list from deterring important DSS work from being published.

*Methods:*

I will follow guidelines for undertaking a systematic review in the format and procedure established by Collaboration for Environmental Evidence (CEE) Evidence Synthesis [@CEE:M-Sg3G8U]. I chose this method of systematic review partially because the topic area is relevant (environmental management), and partially because of the comprehensiveness of the guidelines: the guidelines provides detailed and systematic methods for developing the search strategy, inclusion / exclusion criteria, and coding criteria for evaluating the literature, including pilot searches for refining criteria. The other draw card was the enforced development and pre-registration of the protocol for conducting the review in order to prevent ‘mission creep’ as the review progresses.

In addition, I will use the PRISMA (Preferred Reporting Items for Systematic Reviews, [@Moher:2015]) statement for reporting, as recommended by Nakagawa and Poulin [-@Nakagawa:2012fl]. The PRISMA check-list contains a check-list of 27 reporting items, as well as a flow diagram that visualizes the database searching procedure as well as decisions for including and evaluating studies. The aim of the statement is to increase the transparency of the literature review process.

*Review scope:*

I distinguish between ‘decision *frameworks*’ and ‘decision *tools*’: frameworks may be considered the structured set of procedures governing the approach to an entire decision process - i.e. from problem formulation, to modelling the consequences of decision alternatives, to evaluating alternatives. Structured Decision Making (SDM) is an example of a decision framework [@Bower:2017im]. Decision tools may be understood as the particular procedures or methods used to solve or provide inputs to inform a particular phase in the overarching decision framework. For example, Bayesian Networks, Population Viability Analyses and Multi- Criteria Decision Analysis constitute decision tools. This review will investigate the reproducibility of decisions generated from ‘decision *frameworks*’, rather than just the reproducibility of ‘decision *tools*’.

*Analysis and Reporting:*

By focusing on decision frameworks more broadly – rather than a particular framework, like SDM – I hope to be able to evaluate whether different frameworks might influence the transparency and likely reproducibility of resultant decisions. This should also provide a means of testing the claim that SDMs are increase transparency, and therefore the reproducibility of decisions. Importantly, in not restricting the scope too heavily, this provides a way for dealing with linguistic ambiguity around the language of decision support in ecology and conservation. For example, there is considerable slippage between the terms ‘decision support system’ and ‘decision support tools.’ Although SDM approaches are very common in conservation, restricting the inclusion of studies to nominally SDM studies will likely omit much research that might be decision-analytic in approach, and therefore still constitute a comparable structured or formal framework for decision-making. Following a pilot test of the searching and inclusion criteria, the scope might be revised (i.e. if too many papers are returned).

I am presently unclear on what analyses to conduct. But they will probably include the presentation of some descriptive statistics based around critical evaluation criteria.

------

**Chapter Four: case studies in replicating DSS's**

The final chapters will involve the use of case studies of real-world ecological and conservation decisions. The objective of the case studies is to demonstrate an application of one or several types of reproducibility proposed in the typology in Chapter One. It would also serve as a proof-of-concept for replicating a decision support system. Depending on the degree of complexity and size of the case studies, I could compare a selection of different DSS problems. The exact form of the case studies / experiments will depend on the results from previous chapters, so their specification here remains purposefully vague.

*Environmental water allocations*

Chris Jones has been tasked with demonstrating the benefit of environmental water allocations across Victoria and is seeking collaboration to develop this project. It encompasses multiple river systems, each with multiple management agencies, and so presents the opportunity for a replication experiment, perhaps taking a ‘red card’ approach [@Fidler:2017he]. This could involve giving a problem brief with 2 - 3 objectives, for example, to different teams of researchers, asking them to develop a decision support system, choosing which ever approach or tools that they like. They could be surveyed afterwards, asking them to describe what they did and why. Alternatively, they could write up their methods section for submission afterwards. One issue is that we need to entice people to participate. This could be using funds (which are available). Another approach would be to offer co-authorship.

Importantly, because this is a real-world problem, I will need to ensure that Chris also benefits from this work. Given that Chris’ goals are currently unclear, it is difficult to specify now. However, it could potentially serve as a form of sensitivity analysis, providing evidence about the robustness of different models, but also about the processes used to derive those models. This type of replication analysis would be able to test whether the decision is reasonably robust to different processes, or tools.

*Threatened Woodland Recovery Planning*

This project aims to develop recovery plans for threatened woodland communities by generalising across communities without losing critical aspects of the structure and functioning of each community. The form that this work might take is unclear to me, however, the decision problem poses an interesting case study for work on reproducibility in both ecology and conservation decision-making, because it allows us to explore questions around the role of replications in terms of generality.

------

# Timeline of activities and goals

Attached.

# References
